### ISSUE TITLE
Crash on some files from Desktop menu-based file browser

### ISSUE THREAD

**Issue by nick87720z** [rilian-la-te/vala-panel-appmenu#157]
I just noticed, that in addition to 'Files', showed for desktop window, more items are added.
But when any of Sound, Images or Video is activated, plugin crashes. In case if vala-panel - entire panel crashes. What is good there, is that i managed to run it with gdb. The only problem, is that in case of crush all input is locked, so i was forced to terminate gdb by SIGTERM with its child vala-panel.

Here is gdb output with vala-panel, getting 'Pictures' menu activated (strings backtrace,kill,y are typed by me while program is runing, because after crash, but before kill command, all input is blocked... though kill command did not work by some reason :/ )
```
(gdb) run
Starting program: /usr/bin/vala-panel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffec176700 (LWP 6928)]
[New Thread 0x7fffeb975700 (LWP 6929)]
[New Thread 0x7fffeaf67700 (LWP 6930)]
[New Thread 0x7fffe8f83700 (LWP 6934)]
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 1: no element found

backtrace
kill
y

(vala-panel:6927): GLib-GIO-ERROR **: g_menu_item_set_detailed_action: Detailed action name 'menu.launch-uri('file:///home/nick87720z/%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F/Schroedinger's_cat.png')' has invalid format: 105:expected end of input

Thread 1 "vala-panel" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7b15e51 in ?? () from /usr/lib64/libglib-2.0.so.0
(gdb) 
(gdb) backtrace
#0  0x00007ffff7b15e51 in ?? () from /usr/lib64/libglib-2.0.so.0
#1  0x00007ffff7b16ea5 in g_log_default_handler () from /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff7b171b4 in g_logv () from /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff7b173bf in g_log () from /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff6c125eb in g_menu_item_set_detailed_action () from /usr/lib64/libgio-2.0.so.0
#5  0x00007ffff6c1267e in g_menu_item_new () from /usr/lib64/libgio-2.0.so.0
#6  0x00007ffff6c126a5 in g_menu_insert () from /usr/lib64/libgio-2.0.so.0
#7  0x00007fffe9a8843e in ?? () from /usr/lib64/vala-panel/applets//libappmenu-valapanel.so
#8  0x00007fffe9a894f5 in appmenu_menu_widget_desktop_state_populate_picts () from /usr/lib64/vala-panel/applets//libappmenu-valapanel.so
#9  0x00007ffff6924695 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#10 0x00007ffff6936682 in ?? () from /usr/lib64/libgobject-2.0.so.0
#11 0x00007ffff693f2dc in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#12 0x00007ffff693f6bf in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#13 0x00007ffff6c0eb8c in g_action_change_state () from /usr/lib64/libgio-2.0.so.0
#14 0x00007ffff72b180e in ?? () from /usr/lib64/libgtk-3.so.0
#15 0x00007ffff72b1844 in ?? () from /usr/lib64/libgtk-3.so.0
#16 0x00007ffff7409d61 in ?? () from /usr/lib64/libgtk-3.so.0
#17 0x00007ffff740aeb5 in ?? () from /usr/lib64/libgtk-3.so.0
#18 0x00007ffff6924695 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#19 0x00007ffff6936682 in ?? () from /usr/lib64/libgobject-2.0.so.0
#20 0x00007ffff693f2dc in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#21 0x00007ffff693f6bf in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#22 0x00007ffff75400c2 in gtk_widget_show () from /usr/lib64/libgtk-3.so.0
#23 0x00007ffff73fb975 in ?? () from /usr/lib64/libgtk-3.so.0
#24 0x00007ffff73fc338 in gtk_menu_popup_at_widget () from /usr/lib64/libgtk-3.so.0
#25 0x00007ffff74032bf in ?? () from /usr/lib64/libgtk-3.so.0
#26 0x00007ffff7403db3 in ?? () from /usr/lib64/libgtk-3.so.0
#27 0x00007ffff6924695 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#28 0x00007ffff693605c in ?? () from /usr/lib64/libgobject-2.0.so.0
#29 0x00007ffff693f2dc in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#30 0x00007ffff693f6bf in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#31 0x00007ffff7408206 in ?? () from /usr/lib64/libgtk-3.so.0
#32 0x00007ffff7408430 in ?? () from /usr/lib64/libgtk-3.so.0
#33 0x00007ffff73ea6b1 in ?? () from /usr/lib64/libgtk-3.so.0
#34 0x00007ffff69248c4 in ?? () from /usr/lib64/libgobject-2.0.so.0
#35 0x00007ffff693eaa1 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
---Type <return> to continue, or q <return> to quit---kill
#36 0x00007ffff693f6bf in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#37 0x00007ffff753736c in ?? () from /usr/lib64/libgtk-3.so.0
#38 0x00007ffff73e762e in ?? () from /usr/lib64/libgtk-3.so.0
#39 0x00007ffff73e96ee in gtk_main_do_event () from /usr/lib64/libgtk-3.so.0
#40 0x00007ffff6f2c135 in ?? () from /usr/lib64/libgdk-3.so.0
#41 0x00007ffff6f5d072 in ?? () from /usr/lib64/libgdk-3.so.0
#42 0x00007ffff7b103e7 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#43 0x00007ffff7b10650 in ?? () from /usr/lib64/libglib-2.0.so.0
#44 0x00007ffff7b106fc in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#45 0x00007ffff6c084ad in g_application_run () from /usr/lib64/libgio-2.0.so.0
#46 0x00007ffff633d5d1 in __libc_start_main () from /lib64/libc.so.6
#47 0x000000000040385a in ?? ()
#48 0x00007fffffffcec8 in ?? ()
#49 0x000000000000001c in ?? ()
#50 0x0000000000000001 in ?? ()
#51 0x00007fffffffd3e8 in ?? ()
#52 0x0000000000000000 in ?? ()
```

**Comment by rilian-la-te** [comment]
Do you have some file with strange naming here? I have this crash with exotic main menu items in vala-panel. If those, change filename or font using.

**Comment by darkshram** [comment]
Same thing for me using MATE Desktop applet. In my case, clicking on any menu entry of the desktop menu crashes the panel applet. I have thousands of files inside the Documents, Images and Videos directories (most of them use spanish characters like ñ or á, é, í, ó, ú, etc.). For me, I ended up patching source code and removing the desktop menu entries before distributing RPM packages for my Linux distro.

```
diff -Naur vala-panel-appmenu-0.5.6.orig/lib/appmenu-desktop.vala vala-panel-appmenu-0.5.6/lib/appmenu-desktop.vala
--- vala-panel-appmenu-0.5.6.orig/lib/appmenu-desktop.vala	2017-11-18 06:24:50.000000000 -0600
+++ vala-panel-appmenu-0.5.6/lib/appmenu-desktop.vala	2017-12-13 20:24:24.348084417 -0600
@@ -69,7 +69,7 @@
                 this.add(appmenu);
                 completed_menus |= MenuWidgetCompletionFlags.APPMENU;
             }
-            if ((completed_menus & MenuWidgetCompletionFlags.MENUBAR) == 0)
+            /* if ((completed_menus & MenuWidgetCompletionFlags.MENUBAR) == 0)
             {
                 files_menu = builder.get_object("files") as GLib.Menu;
                 documents_menu = builder.get_object("docs") as GLib.Menu;
@@ -80,7 +80,7 @@
                 var menubar = new Gtk.MenuBar.from_model(gmenu);
                 completed_menus |= MenuWidgetCompletionFlags.MENUBAR;
                 this.add(menubar);
-            }
+            } */
             this.show_all();
         }
         internal void activate_menu_id(SimpleAction action, Variant? param)
```

**Comment by rilian-la-te** [comment]
I want baacktrace, please.

**Comment by rilian-la-te** [comment]
vala-panel do not like single braces (') - this chain filenames. Do you have one of these in folder?

**Comment by rilian-la-te** [comment]
I can made an Quick fix for appmenu only, not for ValaPanel menumodel applet, but this will disable user generation of menu. For appmenu I am too lazy to do it, but for MenuModel this exists. Code is same.

**Comment by rilian-la-te** [comment]
If you want to know, which behaviour we lose, open a ValaPanel config file with launchbar (launchbar should be with custom file launchers) . And show it to me.

**Comment by nick87720z** [comment]
Yep, for all dirs, on which it crashed, reason is files with single quote marks, used as prefix/suffix separator.
I remember fuzzy, where desktop's global menu was almost same as for file manager. Don't remember, what desktop it was.

**Comment by rilian-la-te** [comment]
Gnome-globalmenu AFAIK. It is pretty old.

**Comment by nick87720z** [comment]
This patch fix problem:
```
diff -Naur vala-panel-appmenu-old/lib/appmenu-desktop.vala vala-panel-appmenu/lib/appmenu-desktop.vala
--- vala-panel-appmenu-old/lib/appmenu-desktop.vala     2017-12-17 01:32:15.728100708 +0500
+++ vala-panel-appmenu/lib/appmenu-desktop.vala 2017-12-17 14:53:36.317957070 +0500
@@ -191,8 +191,12 @@
                     var info = file.query_info(FileAttribute.STANDARD_DISPLAY_NAME+","
                                                +FileAttribute.STANDARD_IS_HIDDEN,
                                                FileQueryInfoFlags.NOFOLLOW_SYMLINKS);
-                    if (!info.get_is_hidden())
-                        menu.append(info.get_display_name(),"menu.launch-uri('%s')".printf(file.get_uri()));
+                    if (info.get_is_hidden())
+                        continue;
+
+                    var item = new GLib.MenuItem(info.get_display_name(), null);
+                    item.set_action_and_target("menu.launch-uri", "s", file.get_uri() );
+                    menu.append_item(item);
                 }
             } catch (Error e) {
                 stderr.printf("%s\n",e.message);
```
Still menus are not so convenient, because they display files from subdirs too, like if you run "find ." instead of ls.

**Comment by rilian-la-te** [comment]
Thanks, I will integrate this:-)

**Comment by rilian-la-te** [comment]
closing as fixed for appmenu
