### ISSUE TITLE
Applet crash regularly on xfce4-panel when open and close some qt5 apps

### ISSUE THREAD

**Issue by snippins** [rilian-la-te/vala-panel-appmenu#221]
Tested with dolphin, okular, krusader. If I rapidly close or open and close qt5 windows, the applet will crash and xfce4-panel will ask to restart it.

The relevant debug message: (happen when rapidly closing and open qt apps)

`GLib-CRITICAL **: g_variant_unref: assertion 'value->ref_count > 0' failed`

**Comment by rilian-la-te** [comment]
Version?

**Comment by rilian-la-te** [comment]
And, please, backtrace from GDB, if possible.

**Comment by rilian-la-te** [comment]
Is this fixed by latest commit?

**Comment by snippins** [comment]
Using latest commit 5455c52.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed53a700 (LWP 4063)]
[New Thread 0x7fffecd39700 (LWP 4064)]
[New Thread 0x7fffe7fff700 (LWP 4065)]
[New Thread 0x7fffe77fe700 (LWP 4070)]
[Thread 0x7fffe77fe700 (LWP 4070) exited]
[New Thread 0x7fffe77fe700 (LWP 4593)]

Thread 1 "panel-2-appmenu" received signal SIGSEGV, Segmentation fault.
0x00007ffff5f55d49 in g_variant_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#0  0x00007ffff5f55d49 in g_variant_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#1  0x00007fffee2a222c in glib_autoptr_cleanup_GVariant () from /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so
No symbol table info available.
#2  0x00007fffee2a34b5 in dbus_menu_update_item_properties_from_layout_sync () from /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so
No symbol table info available.
#3  0x00007fffee2a37af in layout_updated_cb () from /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so
No symbol table info available.
#4  0x00007ffff0c48e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#5  0x00007ffff0c488ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#6  0x00007ffff66077c9 in g_cclosure_marshal_generic () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#7  0x00007ffff6606fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#8  0x00007ffff6618fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#9  0x00007ffff6620d51 in g_signal_emitv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#10 0x00007fffee2a6f93 in dbus_menu_xml_proxy_g_signal () from /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libappmenu-xfce.so
No symbol table info available.
#11 0x00007ffff0c48e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#12 0x00007ffff0c488ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#13 0x00007ffff66077c9 in g_cclosure_marshal_generic () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#14 0x00007ffff6606fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#15 0x00007ffff661956e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#16 0x00007ffff6621d6c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#17 0x00007ffff662209f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#18 0x00007ffff39bab5c in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#19 0x00007ffff39aa384 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#20 0x00007ffff5f1974a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#21 0x00007ffff5f19af0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#22 0x00007ffff5f19e12 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#23 0x00007ffff74d3cc5 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#24 0x0000555555557749 in main ()
No symbol table info available.
rax            0x100000001	4294967297
rbx            0x0	0
rcx            0x7ffff7efda00	140737353079296
rdx            0x5555558e3600	93824995964416
rsi            0x7ffff5cacb40	140737317096256
rdi            0x100000001	4294967297
rbp            0x7fffffffc6b0	0x7fffffffc6b0
rsp            0x7fffffffc698	0x7fffffffc698
r8             0x555556185030	93825005015088
r9             0x0	0
r10            0x6a	106
r11            0x0	0
r12            0x0	0
r13            0x7fffffffc8a0	140737488341152
r14            0x7fffffffc820	140737488341024
r15            0x7fffffffc8d0	140737488341200
rip            0x7ffff5f55d49	0x7ffff5f55d49 <g_variant_unref+9>
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

**Comment by rilian-la-te** [comment]
Oops, there was merge conflict and latest commit do not pushed...

**Comment by rilian-la-te** [comment]
Try latest commit now, please.

**Comment by snippins** [comment]
Work nicely! Thanks.
